#include <cmath>

extern "C" {
    // In a real scenario, you would load these weights from a binary file generated by your training script.
    double calculate_confidence(double* features, int feature_count) {
        if (feature_count < 2) return 0.0;

        double speed = features[0];
        double hour = features[1];

        // Hardcoded weights for the hackathon (until you train a real model)
        // High speed = positive weight. Rush hour (e.g., 18.0) = negative weight.
        double w_speed = 0.05;
        double w_hour = -0.15;
        double bias = 2.5;

        double z = (speed * w_speed) + (hour * w_hour) + bias;

        double confidence = 1.0 / (1.0 + std::exp(-z));

        return confidence;
    }
}
