// Alternate Route GeoJSON with Segment-by-Segment Dynamic Traffic Status
// Generated by the ML routing engine (OSMnx / NetworkX) and Polars physics pipeline

export interface TrafficSegmentFeature {
  type: "Feature"
  properties: {
    route_type: "alternate"
    traffic_status: "green" | "amber" | "red"
    speed_estimate_kmh?: number
    segment_name?: string
  }
  geometry: {
    type: "LineString"
    coordinates: [number, number][] // [lng, lat]
  }
}

export interface TrafficRouteCollection {
  type: "FeatureCollection"
  features: TrafficSegmentFeature[]
}

export const ALTERNATE_TRAFFIC_ROUTE: TrafficRouteCollection = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "green",
        speed_estimate_kmh: 38.5,
        segment_name: "Diamond Harbour Bypass Entry",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3652227, 22.5748708],
          [88.3660507, 22.5743206],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "green",
        speed_estimate_kmh: 36.2,
        segment_name: "Circus Avenue Connector",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3660507, 22.5743206],
          [88.3662827, 22.5747869],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "green",
        speed_estimate_kmh: 35.0,
        segment_name: "Beckbagan Row Crossing",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3662827, 22.5747869],
          [88.366175, 22.57495],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "green",
        speed_estimate_kmh: 34.0,
        segment_name: "Syed Amir Ali Avenue Link",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.366175, 22.57495],
          [88.3657008, 22.5755977],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "green",
        speed_estimate_kmh: 32.8,
        segment_name: "Park Circus 7-Point Approach",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3657008, 22.5755977],
          [88.3649941, 22.5763713],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "amber",
        speed_estimate_kmh: 22.4,
        segment_name: "Darga Road Intersection",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3649941, 22.5763713],
          [88.3643162, 22.5768659],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "green",
        speed_estimate_kmh: 33.1,
        segment_name: "Suhrawardy Avenue Flyover Slip",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3643162, 22.5768659],
          [88.3640925, 22.5770363],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "green",
        speed_estimate_kmh: 31.5,
        segment_name: "AJC Bose Road Arterial",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3640925, 22.5770363],
          [88.3626805, 22.5779005],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "red",
        speed_estimate_kmh: 11.2,
        segment_name: "Ripon Street Choke Point",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3626805, 22.5779005],
          [88.3624847, 22.577557],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "red",
        speed_estimate_kmh: 9.8,
        segment_name: "Alimuddin Street Crossing",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3624847, 22.577557],
          [88.3619229, 22.5777158],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "amber",
        speed_estimate_kmh: 21.0,
        segment_name: "Muzaffar Ahmed Street",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3619229, 22.5777158],
          [88.3616799, 22.5777928],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "green",
        speed_estimate_kmh: 30.5,
        segment_name: "Royd Street Corridor",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3616799, 22.5777928],
          [88.3613638, 22.5778978],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "green",
        speed_estimate_kmh: 32.0,
        segment_name: "Rafi Ahmed Kidwai Road",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3613638, 22.5778978],
          [88.36059, 22.578097],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "green",
        speed_estimate_kmh: 29.4,
        segment_name: "Elliot Road Western Branch",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.36059, 22.578097],
          [88.3602608, 22.5768861],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "amber",
        speed_estimate_kmh: 19.8,
        segment_name: "Park Street Crossing Bypass",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3602608, 22.5768861],
          [88.3599476, 22.5759278],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "red",
        speed_estimate_kmh: 12.0,
        segment_name: "Short Street Bottleneck",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3599476, 22.5759278],
          [88.3597846, 22.5752926],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "red",
        speed_estimate_kmh: 10.5,
        segment_name: "Camac Street Junction Delay",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3597846, 22.5752926],
          [88.3587801, 22.5723396],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "green",
        speed_estimate_kmh: 35.6,
        segment_name: "Wood Street Free Flow",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3587801, 22.5723396],
          [88.3591905, 22.5721563],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "red",
        speed_estimate_kmh: 8.5,
        segment_name: "Loudon Street Narrow Choke",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3591905, 22.5721563],
          [88.3598402, 22.5718972],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "amber",
        speed_estimate_kmh: 18.2,
        segment_name: "Rowdon Street Junction",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3598402, 22.5718972],
          [88.3605503, 22.5714834],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "green",
        speed_estimate_kmh: 33.4,
        segment_name: "Hungerford Street Arterial",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3605503, 22.5714834],
          [88.3611751, 22.5710977],
        ],
      },
    },
    {
      type: "Feature",
      properties: {
        route_type: "alternate",
        traffic_status: "red",
        speed_estimate_kmh: 11.0,
        segment_name: "Pretoria Street STCET Feeder Line",
      },
      geometry: {
        type: "LineString",
        coordinates: [
          [88.3611751, 22.5710977],
          [88.3610645, 22.5709118],
        ],
      },
    },
  ],
}

export const TRAFFIC_THEME = {
  green: {
    stroke: "#10B981", // Emerald neon
    glow: "#059669",
    label: "Free Flow (>30 km/h)",
    description: "Optimal bus velocity, zero congestion",
    badge: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
  },
  amber: {
    stroke: "#F59E0B", // Amber warning
    glow: "#D97706",
    label: "Moderate Crawl (15-30 km/h)",
    description: "Peak-hour queue build-up",
    badge: "bg-amber-500/15 text-amber-400 border-amber-500/30",
  },
  red: {
    stroke: "#EF4444", // Crimson gridlock
    glow: "#DC2626",
    label: "Bottleneck Delay (<15 km/h)",
    description: "Severe intersection bottleneck",
    badge: "bg-red-500/15 text-red-400 border-red-500/30",
  },
} as const
